### ISSUE TITLE
Not able login on macos

### ISSUE THREAD

**Issue by devender-yadav** [xx10t4/iota1k#10]
Hi Team,

I am using `iota1k-0.0.6` on MacOS.

I am not able to proceed from the login page.

Below mentioned error is shown **at the time of opening the login page** on console in chrome dev tool- 

    [Uncaught Error: dlopen(/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/.iota1k.CgBXLk, 1): no suitable image found.  Did find:
	/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/.iota1k.CgBXLk: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/private/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/AppTranslocation/C…s/Resources/app.asar/node_modules/ref/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/private/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/AppTranslocation/C…7D7/d/iota1k.app/Contents/Resources/app.asar/node_modules/ref/lib/ref.js:5:47)](url)Uncaught Error: dlopen(/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/.iota1k.CgBXLk, 1): no suitable image found.  Did find:
	/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/.iota1k.CgBXLk: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/private/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/AppTranslocation/C…s/Resources/app.asar/node_modules/ref/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/private/var/folders/lq/kdm36dnj6sz3cs_hcxc1d96r0000gn/T/AppTranslocation/C…7D7/d/iota1k.app/Contents/Resources/app.asar/node_modules/ref/lib/ref.js:5:47)

Nothing happens on clicking `Login` button.

-Dev

**Comment by mathanimas** [comment]
Same here.
