### ISSUE TITLE
Start with NPM causes error on OSX

### ISSUE THREAD

**Issue by jakedunc** [xx10t4/iota1k#2]
Getting the following error:

> export NODE_ENV=development || set NODE_ENV=development && electron .

App threw an error during load
Error: Cannot find module 'i18next'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/SDHD/Crypto/Coins/IOTA/iota1k-master/app/js/main.js:29:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by jakedunc** [comment]
More than happy to be the OSX platform tester. Really keen to get this up and running on my machine and make some fixes on the UI.

**Comment by mathanimas** [comment]
Don't know if this is related or something different. I get the following error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
ReferenceError: app is not defined
    at buildMenu (/private/var/folders/gm/md7p9r411v37nnz38w5dj68r0000gn/T/AppTranslocation/9A07E8AD-1D42-4310-8529-6F075E19D7C7/d/iota1k.app/Contents/Resources/app.asar/app/js/menu.js:85:22)
    at App.createWindow (/private/var/folders/gm/md7p9r411v37nnz38w5dj68r0000gn/T/AppTranslocation/9A07E8AD-1D42-4310-8529-6F075E19D7C7/d/iota1k.app/Contents/Resources/app.asar/app/js/main.js:45:3)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

**Comment by matthisk** [comment]
Getting the same error @mathanimas is receiving on startup of the app. (OS X)

**Comment by xx10t4** [comment]
@mathanimas I think that is something different, though still probably OSX specific. I  assume you downloaded and installed the binary version of the app, not running it from the unpackaged code? Could you open a separate issue for the Javascript error?

**Comment by xx10t4** [comment]
@jakedunc Are you running the unpackaged code (as opposed to a compiled binary)? Assuming yes, can you run `npm install` in the project root dir and post the output here?

**Comment by mathanimas** [comment]
@xx10t4 Sure, no problem. Will do.

**Comment by jakedunc** [comment]
Yes @xx10t4 my bad, I npm installed a different directory. But yes now I am getting the same "app is not defined" issue as above.
