### ISSUE TITLE
Crash when sending two messages: TypeError: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by joepio** [xx10t4/iota1k#5]
When sending two messages simultaneously, the GUI crashes and I get this error in the Console:

````
Thread Hashing...
I: Starting search threads.
Welcome to CCURL 0.2.1, home of the ccurl. can I take your vector?
Pow Finished.
I: Found threads. Returning.
Welcome to CCURL 0.2.1, home of the ccurl. can I take your vector?
Thread Hashing...
/home/joep/dev/coins/iota1k/node_modules/ccurl.interface.js/index.js:116
                var txHash = newTxObject.hash;
                                        ^

TypeError: Cannot read property 'hash' of undefined
    at /home/joep/dev/coins/iota1k/node_modules/ccurl.interface.js/index.js:116:41
    at /home/joep/dev/coins/iota1k/node_modules/ffi/lib/_foreign_function.js:115:9
I: Starting search threads.
I: Found threads. Returning.
Pow Finished.
````

And thanks for sharing this project! It's awesome.

**Comment by xx10t4** [comment]
This should be fixed in the latest release https://github.com/xx10t4/iotalk/releases/tag/0.1.2. Transactions are now queued for POW so ccurl only operates on one at a time.
