### ISSUE TITLE
Crash on start in OS X

### ISSUE THREAD

**Issue by mathanimas** [xx10t4/iota1k#6]
Cool project, thanks for sharing!

When starting the app (pre-compiled binary, version 0.0.5, downloaded from Github), I get the following error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
ReferenceError: app is not defined
    at buildMenu (/private/var/folders/gm/md7p9r411v37nnz38w5dj68r0000gn/T/AppTranslocation/9A07E8AD-1D42-4310-8529-6F075E19D7C7/d/iota1k.app/Contents/Resources/app.asar/app/js/menu.js:85:22)
    at App.createWindow (/private/var/folders/gm/md7p9r411v37nnz38w5dj68r0000gn/T/AppTranslocation/9A07E8AD-1D42-4310-8529-6F075E19D7C7/d/iota1k.app/Contents/Resources/app.asar/app/js/main.js:45:3)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

**Comment by harryrford** [comment]
![screen shot 2017-09-08 at 10 02 27 am](https://user-images.githubusercontent.com/31749679/30190266-829a9256-947c-11e7-990e-4b587caa7dc1.png)
Same problem here, running latest version of java alongside OS X 10.11.6
Massive thanks for supporting the IOTA platform!

**Comment by xx10t4** [comment]
Please check out version 0.0.6. Hopefully this issue is fixed but I have no way to test it myself. Btw, this app does not need Java at all.

**Comment by mathanimas** [comment]
I downloaded version 0.0.6 which apparently fixes this JavaScript error. I think that this issue may be closed now. However, I now experience the symptoms mentioned in [issue #10](https://github.com/xx10t4/iota1k/issues/10).

**Comment by nclr** [comment]
I still have the same problem with 0.0.6

**Comment by xx10t4** [comment]
@nclr Are you having the same issue noted here ("Reference Error: app is undefined"), or are you now having the issue in https://github.com/xx10t4/iota1k/issues/10 ?

**Comment by jakedunc** [comment]
The app now opens on mac, but entering a seed and clicking Login doesn't do anything..

**Comment by zmarwa** [comment]
same for me on mac. Any solution to login please?
